name: CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with: 
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /reactjs/erparasrai/
        local-dir: build/
        protocol: ftp
        port: 21
  # web-deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Get latest code
  #     uses: actions/checkout@v2
  #   - name: Sync Files
  #     uses: SamKirkland/FTP-Deploy-Action@4.3.3
  #     with: 
  #       server: ${{ secrets.FTP_SERVER }}
  #       username: ${{ secrets.FTP_USERNAME }}
  #       password: ${{ secrets.FTP_PASSWORD }}
  #       server-dir: /reactjs/erparasrai/
  #       local-dir: build/
  #       protocol: ftp
  #       port: 21